HAI 1.3

I HAS A l ITZ 0
I HAS A o ITZ QUOSHUNT OF 4.0 AN 1.0
IM IN YR loop UPPIN YR i TIL BOTH SAEM i AN 151
VISIBLE o
BOTH SAEM i AN 0
O RLY?
YA RLY

NO WAI
BOTH SAEM l AN 0
O RLY?
YA RLY
  o R DIFF OF o AN QUOSHUNT OF 4.0 AN SUM OF 1.0 AN PRODUKT OF i AN 2.0
  l R 1
NO WAI
  o R SUM OF o AN QUOSHUNT OF 4.0 AN SUM OF 1.0 AN PRODUKT OF i AN 2.0
  l R 0
OIC
OIC

IM OUTTA YR loop
VISIBLE o

KTHXBYE
